name: Update File

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 8,12,16 * * *"

jobs:
  update-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Pull changes from main
        run: |
          git checkout main
          git pull origin main
      - name: Update file
        run: |
          echo "Hello, world!" >> example.txt
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Moez Nazir
          author_email: moeznazir47@gmail.com
          message: "Update file automatically"

      - name: Push changes
        run: |
          git push origin main